{
 "title": "GitLab JiHu - Gitaly",
 "description": "Self-defined Dashboard for gitaly of GitLab JiHu",
 "tags": [ "gitaly" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"$job\"}, instance)"
    }
   },
   { "name": "job", "query": "gitaly,praefect-gitaly" }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gitaly_connections_total{instance=~\"$instance\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(gitaly_housekeeping_tasks_total{instance=~\"$instance\"})",
     "legendFormat": "Housekeeping Tasks"
    }
   ]
  },
  {
   "title": "Git Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "topk(1, count by (git_version) (gitlab_build_info{instance=~\"$instance\"}))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests by Clients",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client_name) (gitaly_service_client_requests_total{instance=~\"$instance\"})",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Git Methods ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(gitaly_command_real_seconds_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum without (grpc_method,grpc_service,grpc_type) (\n  rate(grpc_server_started_total{instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"gitaly\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "avg(go_memstats_next_gc_bytes{instance=~\"$instance\"})",
     "legendFormat": "Next GC"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_goroutines{instance=~\"$instance\"})",
     "legendFormat": "Go routines"
    },
    {
     "expr": "avg(process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "Open FDs (file descriptors)"
    }
   ]
  },
  { "title": "Housekeeping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Waiting",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "gitaly_gitlab_api_latency_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{le}}"
    },
    {
     "expr": "gitaly_hook_transaction_voting_delay_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Housekeeping Pruned Files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(filetype) (gitaly_housekeeping_pruned_files_total{instance=~\"$instance\"}) ",
     "legendFormat": "{{filetype}}"
    }
   ]
  }
 ]
}