{
 "title": "GitLab JiHu - Machine Performance",
 "description": "Self-defined Dashboard for nodes of GitLab JiHu",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(node_boot_time_seconds)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$instance\"} * 1000",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=~\"$instance\"} * 1000",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_timex_sync_status{instance=\"$instance\"}",
     "legendFormat": "NTP Enabled"
    },
    {
     "expr": "node_timex_offset_seconds{instance=\"$instance\"}",
     "legendFormat": "NTP Offset"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))",
     "legendFormat": "Core"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mem"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\"}) ",
     "legendFormat": "Disk"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "Openfiles"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "ContextSwitch"
    }
   ]
  },
  { "title": "Average Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Load Average",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_load1{instance=~\"$instance\"}) / max(count(node_cpu_seconds_total{instance=~\"$instance\", mode=~\"system\"}))",
     "legendFormat": "1m"
    },
    {
     "expr": "max(node_load5{instance=~\"$instance\"}) / max(count(node_cpu_seconds_total{instance=~\"$instance\", mode=~\"system\"}))",
     "legendFormat": "5m"
    },
    {
     "expr": "max(node_load15{instance=~\"$instance\"}) / max(count(node_cpu_seconds_total{instance=~\"$instance\", mode=~\"system\"}))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=~\"idle\"}[2m])))",
     "legendFormat": "CPU"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance\"} - (node_memory_MemFree_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"})) / node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "MEM"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=~\"iowait\"}[2m]))",
     "legendFormat": "IOWAIT"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffers/Cached"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}-Reads"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}-Writes"
    },
    {
     "expr": "sum by (instance) (node_disk_io_now{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}-CurrentIO"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_read_time_seconds_total{instance=~\"$instance\"}[5m])) / sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}-Read-consuming"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_write_time_seconds_total{instance=~\"$instance\"}[5m])) / sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}-Write-consuming"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$instance\",fstype=~\"ext4|xfs|nfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~\"$instance\",fstype=~\"ext4|xfs|nfs\"} / node_filesystem_size_bytes{instance=\"$instance\",fstype=~\"ext4|xfs|nfs\"})"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=~\"$instance\",fstype=~\"ext4|xfs|nfs\"})"
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{instance=~\"$instance\",device!~\"tap.*|veth.*|br.*|docker.*|virbr*|lo*|nointernet*\"}[5m]))",
     "legendFormat": "{{instance}}-{{device}}-receive"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{instance=~\"$instance\",device!~\"tap.*|veth.*|br.*|docker.*|virbr*|lo*|nointernet*\"}[5m]))",
     "legendFormat": "{{instance}}-{{device}}-transmit"
    }
   ]
  }
 ]
}