{
 "title": "GitLab JiHu - NGINX VTS",
 "description": "Self-defined Dashboard for nginx of GitLab JiHu",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"nginx\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count by (hostname) (nginx_vts_info{instance=~\"$instance\"}))",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "topk(1, count by (version) (nginx_vts_info{instance=~\"$instance\"}))",
     "legendFormat": " {{version}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(nginx_vts_upstream_request_seconds_total{instance=~\"$instance\"}[$__interval])\n) /\nsum by (instance) (\n  rate(nginx_vts_upstream_requests_total{instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Shared Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (shared) (nginx_vts_main_shm_usage_bytes{instance=~\"$instance\", job=~\"nginx\"})",
     "legendFormat": "{{shared}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Server - Current total of incoming / outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (instance) (\n  rate(nginx_vts_server_bytes_total{instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "{{direction}}-{{host}}"
    }
   ]
  },
  {
   "title": "Upstream - Current total of incoming / outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without (instance) (\n  rate(nginx_vts_upstream_bytes_total{instance=~\"$instance\"}[5m])\n)",
     "legendFormat": "{{direction}}-{{backend}}-{{upstream}}"
    }
   ]
  },
  { "title": "Requests by HTTP code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Server - Requests by HTTP code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance) (\n  rate(nginx_vts_server_requests_total{instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "{{code}} {{host}}"
    }
   ]
  },
  {
   "title": "Upstream - Requests by HTTP code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (instance) (\n  rate(nginx_vts_upstream_requests_total{instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "{{code}} {{backend}} {{upstream }}"
    }
   ]
  }
 ]
}