{
 "title": "GitLab JiHu - PostgreSQL",
 "description": "Self-defined Dashboard for postgresql of GitLab JiHu\r\n",
 "tags": [ "postgresql" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~'postgres'},instance)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(pg_postmaster_start_time_seconds{instance=~\"$instance\"} * 1000)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Shared Buffers"
    },
    {
     "expr": "pg_settings_wal_buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "WAL Buffers"
    },
    {
     "expr": "pg_settings_work_mem_bytes{instance=~\"$instance\"}",
     "legendFormat": "Work Mem"
    },
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=~\"$instance\"}",
     "legendFormat": "Maintenance Work Mem"
    },
    {
     "expr": "pg_settings_temp_buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "Temp Buffers"
    },
    {
     "expr": "pg_settings_wal_buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "WAL Buffers"
    },
    {
     "expr": "pg_settings_wal_segment_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "WAL Segment Size"
    },
    {
     "expr": "pg_settings_wal_keep_segments{instance=~\"$instance\"}",
     "legendFormat": "WAL Keep Segments"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=~\"$instance\"}",
     "legendFormat": "Max Workers"
    },
    {
     "expr": "pg_settings_max_parallel_workers{instance=~\"$instance\"}",
     "legendFormat": "Max Parallel Workers"
    },
    {
     "expr": "pg_settings_max_parallel_workers_per_gather{instance=~\"$instance\"}",
     "legendFormat": "Max Parallel Workers Per Gather"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\"})",
     "legendFormat": " Current Conn"
    },
    {
     "expr": "pg_settings_max_connections{instance=~\"$instance\"}",
     "legendFormat": " {{instance}}-Max Conn"
    }
   ]
  },
  {
   "title": "Replication Lag ",
   "type": "stat",
   "description": "Lag behind master in seconds.\n\nOnly available on a standby System.",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag{instance=\"$instance\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"})",
     "legendFormat": "Tuples Inserted"
    },
    {
     "expr": "sum(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})",
     "legendFormat": "Tuples Updated"
    },
    {
     "expr": "sum(pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"})",
     "legendFormat": "Tuples Deleted"
    },
    {
     "expr": "sum(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})",
     "legendFormat": "Tuples Fetched"
    },
    {
     "expr": "sum(pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"})",
     "legendFormat": "Tuples Returned"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{instance=~\"$instance\",datname!~\"template.*|postgres.*\"}) by (datname)",
     "legendFormat": " {{datname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$instance\"})",
     "legendFormat": "CurrConn"
    },
    {
     "expr": "sum(pg_settings_max_connections{instance=~\"$instance\"})",
     "legendFormat": "MaxConn"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$instance\"}) * 100 / sum(pg_settings_max_connections{instance=~\"$instance\"})",
     "legendFormat": "RatioConn"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$instance\",state!~\"idle\"}) * 100 / sum(pg_stat_activity_count{instance=~\"$instance\"})",
     "legendFormat": "SaturationConn"
    },
    {
     "expr": "sum(pg_stat_activity_count{instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=~\"$instance\",datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=~\"$instance\"} + pg_stat_database_blks_hit{instance=~\"$instance\"})",
     "legendFormat": "Cache Hit Ratio - {{datname}} "
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{instance=~\"$instance\"}[1m])) by (datname) !=0",
     "legendFormat": "commit-{{datname}}"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{instance=~\"$instance\"}[1m])) by (datname) !=0",
     "legendFormat": "rollback-{{datname}}"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_max_tx_duration{instance=~\"$instance\"}) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_database_deadlocks{instance=~\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=~\"$instance\",datname=~\"$datname\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "IO Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "I/O Read/Write Time",
   "type": "timeseries",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (pg_stat_database_blk_read_time{instance=~\"$instance\",datname=~\"$datname\"})",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum (pg_stat_database_blk_write_time{instance=~\"$instance\",datname=~\"$datname\"})",
     "legendFormat": "blk_write_time"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "write_time"
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "sync_time"
    }
   ]
  }
 ]
}